[package]
name = "srml-pow"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
srml-support = { path = "../support", default-features = false }
timestamp = { package = "srml-timestamp", path = "../timestamp", default-features = false }
pow-primitives = { package = "substrate-consensus-pow-primitives", path = "../../core/consensus/pow/primitives", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
runtime-io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
primitives = { package = "substrate-primitives", path = "../../core/primitives", default-features = false }

[features]
default = ["std"]
std = [
	"srml-support/std",
	"timestamp/std",
	"pow-primitives/std",
	"codec/std",
	"rstd/std",
	"sr-primitives/std",
	"runtime-io/std",
	"serde",
	"primitives/std",
]
